export const classes = {
  pageContainer: {
    display: "flex",
    height: "100vh",
    background: "linear-gradient(to right, #b2dfdb, #80cbc4)",
  },
  sidebar: {
    width: "20%",
    backgroundColor: "#ffab91",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "20px",
    borderRadius: "15px 0 0 15px",
  },
  sidebarButton: {
    width: "100%",
    color: "#000",
    marginBottom: "15px",
    padding: "10px 0",
    borderRadius: "12px",
    fontWeight: "bold",
    textTransform: "none",
    "&:hover": { backgroundColor: "#e0e0e0" },
  },
  mainContent: {
    flexGrow: 1,
    margin: "20px",
    borderRadius: "10px",
    backgroundColor: "#ffffff",
    boxShadow: "0px 4px 10px rgba(0, 0, 0, 0.2)",
    padding: "20px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#ffab91",
    padding: "10px 20px",
    borderRadius: "10px 10px 0 0",
    marginBottom: "10px",
  },
  quizCard: {
    margin: "10px 0",
    padding: "15px",
    borderRadius: "10px",
    backgroundColor: "#ffa07a",
    boxShadow: "0px 4px 6px rgba(0,0,0,0.1)",
    color: "#fff",
    fontWeight: "bold",
    cursor: "pointer",
  },
};
